# Name of our automated workflow
name: Build and Deploy to Local Kubernetes

# This workflow runs on any push to the "main" branch
on:
  push:
    branches: [ "main" ]

# A workflow is made of one or more "jobs" that run in sequence or in parallel
jobs:
  build-and-deploy:
    # This job will run on a fresh virtual machine hosted by GitHub
    runs-on: ubuntu-latest

    # These are the sequential steps the job will take
    steps:
      # Step 1: Check out your repository's code onto the runner
      - name: Checkout Code
        uses: actions/checkout@v3

      # Step 2: Set up Docker Buildx (a modern tool for building images)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Step 3: Build the Docker image
      # The '--load' flag is CRITICAL. It loads the built image directly into the Docker
      # daemon on the runner, making it available to the kubectl in the next step.
      - name: Build and load Docker image
        run: docker build -t souls:latest . --load

      # Step 4: Apply the deployment and service manifests to Kubernetes
      # This is the EXACT same command you ran manually on your computer!
      - name: Deploy to Kubernetes
        run: kubectl apply -f deployment.yaml -f service.yaml